<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Wms.Supplier.Application.Contracts</AssemblyName>
    <RootNamespace>Wms.Supplier.Application.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Core" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Authorization" Version="$(AbpVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wms.Supplier.Domain\Wms.Supplier.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Wms.Shared\Wms.Shared.csproj" />
  </ItemGroup>
</Project>
