<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Wms.Production.HttpApi.Client</AssemblyName>
    <RootNamespace>Wms.Production.HttpApi.Client</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Http.Client" Version="$(AbpVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wms.Production.Application.Contracts\Wms.Production.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
