<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Wms.Material.HttpApi</AssemblyName>
    <RootNamespace>Wms.Material.HttpApi</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="$(AbpVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wms.Material.Application\Wms.Material.Application.csproj" />
    <ProjectReference Include="..\Wms.Material.Application.Contracts\Wms.Material.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
