<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Wms.Warehouse.HttpApi</AssemblyName>
    <RootNamespace>Wms.Warehouse.HttpApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="$(AbpVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wms.Warehouse.Application\Wms.Warehouse.Application.csproj" />
    <ProjectReference Include="..\Wms.Warehouse.Application.Contracts\Wms.Warehouse.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
