<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Wms.Material.EntityFrameworkCore</AssemblyName>
    <RootNamespace>Wms.Material.EntityFrameworkCore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" Version="$(AbpVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EfCoreVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wms.Material.Domain\Wms.Material.Domain.csproj" />
  </ItemGroup>
</Project>
