<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Wms.DbMigrator</AssemblyName>
    <RootNamespace>Wms.DbMigrator</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Core" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Autofac" Version="$(AbpVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EfCoreVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(EfCoreVersion)" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog" Version="$(SerilogVersion)" />
    <PackageReference Include="Serilog.Sinks.File" Version="$(SerilogSinksFileVersion)" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="$(SerilogExtensionsLoggingVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Wms.EntityFrameworkCore.SqlServer\Wms.EntityFrameworkCore.SqlServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>